### ISSUE TITLE
DB create fails with "error in your SQL syntax"

### ISSUE THREAD

**Issue by jimlei** [BlueHotDog/sails-migrations#60]
Just did a clean install
````
vagrant@vagrant-ubuntu-trusty-64:/vagrant/server$ sails --version
0.11.0

vagrant@vagrant-ubuntu-trusty-64:/vagrant/server$ sails-migrations --version
sails_migrations CLI version:  2.0.7
Local sails_migrations version:  2.0.7

vagrant@vagrant-ubuntu-trusty-64:/vagrant/server$ sails-migrations db:create
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"myDbName"' at line 1
    at Query.Sequence._packetToError
````

````
  developmentMysqlServer: {
    adapter: 'sails-mysql',
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'api'
  },

**Comment by sahanDissanayake** [comment]
@BlueHotDog , Same here on sails V0.10.5 and I even tried this using your own example app with my own Model and mysql

Error on > sails-migrations status
```javascript
Error: ENOENT, scandir '/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/db/migrations'
    at Error (native)
From previous event:
    at Migrator_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/migrate/index.js:96:43)
From previous event:
    at Runner_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/lib/sails-migrations/status.js:15:36)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at /Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/lib/sails-migrations/status.js:14:8
    at process._tickCallback (node.js:355:11)

```


Error on > sails-migrations db:create
```javascript
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"sails_migrations_test_0_10_5"' at line 1
    at Query.Sequence._packetToError (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    at Protocol._enqueue (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/mysql/lib/Connection.js:185:25)
    at /Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/dialects/mysql/runner.js:42:16
From previous event:
    at Runner_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/dialects/mysql/runner.js:41:10)
From previous event:
    at Runner_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/runner.js:125:15)
From previous event:
    at Runner_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/runner.js:46:19)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Runner_MySQL.<anonymous> (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/runner.js:31:6)
From previous event:
    at Raw_MySQL.Target.then (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/node_modules/knex/lib/interface.js:27:33)
    at Function.DatabaseTasks.executeQuery (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/lib/sails-migrations/helpers/database_tasks.js:21:19)
    at DatabaseTasks.create (/Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/lib/sails-migrations/helpers/database_tasks.js:34:17)
    at /Applications/MAMP/htdocs/sails-migrations/test/fixtures/sample_apps/0.10.5/node_modules/sails-migrations/lib/sails-migrations/create_database.js:8:51
    at process._tickCallback (node.js:355:11)
```
